[dist]
cargo-dist-version = "0.14"
artifacts = ["executable"]
targets = [
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
  "aarch64-unknown-linux-musl",
  "x86_64-unknown-linux-musl",
  "aarch64-pc-windows-msvc",
  "x86_64-pc-windows-msvc",
]
installers = ["shell", "powershell"]

[dist.github]
repo = "purlity/rectiq"

