name: aur (rectiq-bin)

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (e.g., rectiq-cli-v0.1.0)"
        required: true
        type: string

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  aur:
    name: AUR Publish
    # Only run in the public repo, and only for final releases
    if: ${{ github.repository == 'purlity/rectiq' && (github.event_name == 'workflow_dispatch' || (github.event_name == 'release' && github.event.release.prerelease == false)) }}
    runs-on: ubuntu-latest
    env:
      AUR_SSH_PRIVATE_KEY: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
      AUR_KNOWN_HOSTS: ${{ secrets.AUR_KNOWN_HOSTS }}
      AUR_REPO_URL: ${{ secrets.AUR_REPO_URL }}
      AUR_EMAIL: ${{ secrets.AUR_EMAIL }}
    steps:
      - name: Skip if AUR key missing
        if: ${{ env.AUR_SSH_PRIVATE_KEY == '' }}
        run: echo "AUR_SSH_PRIVATE_KEY not set; skipping." && exit 0

      - uses: actions/checkout@v4

      - name: Prepare AUR repo and push PKGBUILD
        if: ${{ env.AUR_SSH_PRIVATE_KEY != '' }}
        run: |
          set -euxo pipefail
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            TAG="${{ github.event.inputs.tag }}"
          else
            TAG="${{ github.event.release.tag_name }}"
          fi
          VER="${TAG#rectiq-cli-v}"
          sed -i "s/\${VERSION_FROM_TAG}/${VER}/g" aur/PKGBUILD

          mkdir -p ~/.ssh
          printf %s "${AUR_SSH_PRIVATE_KEY}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          printf %s "${AUR_KNOWN_HOSTS}" > ~/.ssh/known_hosts

          git clone "${AUR_REPO_URL}" aur-out
          cp aur/PKGBUILD aur-out/
          cd aur-out
          git config user.name "rectiq-bot"
          git config user.email "${AUR_EMAIL}"
          git add PKGBUILD
          git commit -m "rectiq-bin ${VER}" || echo "No changes to commit"
          git push
